//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TP_WEB_ASP.NET_Menendez_Rasjido
{
    public partial class Detalles_de_Productos
    {
    }
}
